### PR TITLE
fix thrift types declaration order

### PR DESCRIPTION
**Pull request by simbs**
Fixes issue #81 with thrift for Python (# objects should be declared before being used as a property in others.

Also changed all property names to camel case - is this going to be an issue with .NET and Node?

### CODE REVIEW

**Comment by chackett** [comment]
I am happy to accept this for now but would like to raise the following:

It is not the intention of Thrift that the IDL files are consumed directly at run/build time of client application. It was intended that the Thrift code generator be used. With this in mind I would think that the Thrift IDL files should be copied into the Python projects (or any other project that consumes them directly) to avoid issue.

I don't think the main .thrift files should be updated / tweaked based on requirements of a client app. Imagine for example Python wanted them in one order and another language wanted them in another. It's not practical to constantly patch the .thrift.

One solution is to pull the thrift file into your project I think, @simbs that is what @kevingordonwp has done.

What do you think @andybrodie

**Comment by andybrodie** [comment]
I agree with @chackett  that any generated artifacts of the Thrift wrapper should be abstracted by the wrapper, to permit replacement of Thrift with something else later with no impact on the client app (i.e. the app that is using the wrapper).

That said, re-organising the content of the IDL files in a logical manner and agreeing a consistent format for naming is a good idea.  Have we moved towards a "thrift standard", or is there no such thing?  The only reference I can find is in the [(missing manual):](https://diwakergupta.github.io/thrift-missing-guide/)

> While the Thrift compiler does not enforce any naming conventions, it is advisable to stick to standard naming conventions otherwise you may be in for some surprises. For instance, if you have a struct named tweetSearchResults (note the mixedCase), the Thrift compiler will generated a Java file named TweetSearchResults (note the CamelCase) containing a class named tweetSearchResults (like the original struct). This will obviously not compile under Java.

Given this, and looking at the changes that @simbs has proposed, I think this was a good thing for us to do to make things easier for wrapper development.  I don't think we'll need further changes in terms of style, after all, just changing the functionality.

**Comment by simbs** [comment]
@chackett I did that originally, and you suggested we should change the declaration order in the main files too (#81). I will have to keep a copy of the files in the python wrapper folder anyway, it's not about the specific wrapper.

I don't think we will have issues with any language as long as the objects are declared in order of appearance, if it's compiled it doesn't matter, if it's interpreted this is the right order. 

On casing, I only changed a few lines where a different one was used, it was already camelCase in most of the properties; the struct naming was already consistent.

**Comment by chackett** [comment]
That's cool thanks @andybrodie .

Also, my apologies @simbs I do remember saying something like that.

It's a catch 22 I think but I think @andybrodie has a nice suggestion. We agree on a format for the main thrift IDL files to prevent disruption.

Thanks.

**Pull request merged**
